language: python
cache: pip
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
install:
  - pip install -r requirements.txt
  - pip install flake8
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then flake8 shipyard.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then flake8 shipyard.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then flake8 cascade/*.py; fi

